id: d6_realname_settings
label: Realname 6 configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - realname_pattern
process:
  pattern:
    plugin: realname_replace_token
    source:
      - realname_pattern
destination:
  plugin: config
  config_name: realname.settings
